version: "3"

networks:
   alice:

services:
  db:
    image: postgres:14-alpine3.16
    container_name: db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build: ./backend
    container_name: backend
    restart: always
    volumes:
      - ./data/backend:/data
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    volumes:
      - ./data/frontend:/data
    ports:
      - "80:80"
    depends_on:
      - backend